[package]
name = "ferric-qwen3-tp-fp32-head32-kernels-device-v8"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[features]
default = ["gfx950"]
gfx950 = []

[dependencies]
fe2o3-device = { git = "https://github.com/harsh-nod/fe2o3.git", rev = "4f6f65ce22222bae9ece5c5f08c66e56e022a9e4", version = "=0.1.0" }

[target.'cfg(not(target_arch = "amdgpu"))'.dependencies]
fe2o3-host = { git = "https://github.com/harsh-nod/fe2o3.git", rev = "4f6f65ce22222bae9ece5c5f08c66e56e022a9e4", version = "=0.1.0" }

[dev-dependencies]
syn = { version = "=2.0.119", features = ["full"] }

[lib]
name = "ferric_qwen3_tp_fp32_head32_kernels_device_v8"
path = "src/lib.rs"
