[package]
name = "ferric-spec"
description = "Executable sequential semantics for Ferric inference"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
vstd.workspace = true

[package.metadata.verus]
verify = true

[lints]
workspace = true
