[package]
name = "ferric-qwen3-all-kernels-device-v1"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace]

[dependencies]
fe2o3-device = { git = "https://github.com/harsh-nod/fe2o3.git", rev = "ff21f24f5349d78583a2a832ba3aa37bf3e0846c", version = "=0.1.0" }

[target.'cfg(not(target_arch = "amdgpu"))'.dependencies]
fe2o3-host = { git = "https://github.com/harsh-nod/fe2o3.git", rev = "ff21f24f5349d78583a2a832ba3aa37bf3e0846c", version = "=0.1.0" }

[dev-dependencies]
syn = { version = "2", features = ["full"] }

[lib]
name = "ferric_qwen3_all_kernels_device_v1"
path = "src/lib.rs"
