//! Cooperative target telemetry for the direct-KFD debugger.
//!
//! This channel carries bounded declarations made by the debug target. Linux
//! credentials attribute each received packet to the process captured by the
//! debugger, but they do not make the declared artifact, dispatch, allocation,
//! or diagnostic content true. In particular, this protocol does not prove
//! that a code object was loaded, a dispatch reached KFD or a GPU, an
//! allocation exists, or a diagnostic describes an observed fault. Consumers
//! must retain the `declared` truth class and correlate these records with
//! independent KFD observations and admitted artifact bytes.
//!
//! The inherited `AF_UNIX` `SOCK_SEQPACKET` endpoint grants no KFD, ptrace,
//! target-memory, register, queue-control, or filesystem authority. Wire
//! records contain only fixed enums, bounded integer metadata, lengths, and
//! opaque 32-byte identities. They never encode paths, native pointers,
//! addresses, or file descriptors. The session nonce prevents accidental
//! cross-session correlation; it is not a secret or an authentication key.

use std::error::Error;
use std::fmt;
use std::fs::File;
use std::io::{IoSliceMut, Read};
use std::mem::MaybeUninit;
use std::os::fd::{FromRawFd, OwnedFd};

use rustix::net::sockopt::{
    set_socket_passcred, socket_domain, socket_passcred, socket_peercred, socket_type,
};
use rustix::net::{
    AddressFamily, RecvAncillaryBuffer, RecvAncillaryMessage, RecvFlags, ReturnFlags, SendFlags,
    SocketFlags, SocketType, getpeername, recvmsg, send, socketpair,
};
use sha2::{Digest, Sha256};

/// Exact byte length of every V1 telemetry packet.
pub const KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1: usize = 256;
pub const KFD_TARGET_DEBUG_TELEMETRY_FD_ENV_V1: &str = "FE2O3_KFD_DEBUG_TELEMETRY_FD_V1";
pub const KFD_TARGET_DEBUG_TELEMETRY_NONCE_ENV_V1: &str = "FE2O3_KFD_DEBUG_TELEMETRY_NONCE_V1";
pub const KFD_TARGET_DEBUG_TELEMETRY_DEBUGGER_PID_ENV_V1: &str =
    "FE2O3_KFD_DEBUG_TELEMETRY_DEBUGGER_PID_V1";

const MAGIC_V1: [u8; 8] = *b"F2KDTL1\0";
const VERSION_V1: u16 = 1;
const HEADER_LEN_V1: usize = 56;
const CHECKSUM_OFFSET_V1: usize = 224;
const PAYLOAD_CAPACITY_V1: usize = CHECKSUM_OFFSET_V1 - HEADER_LEN_V1;
const CHECKSUM_DOMAIN_V1: &[u8] = b"fe2o3-kfd-target-debug-telemetry-record-v1\0";
const MAX_PROC_STAT_BYTES_V1: u64 = 16 * 1024;
const MAX_PROC_STATUS_BYTES_V1: u64 = 128 * 1024;

/// An opaque logical identity carried by cooperative telemetry.
///
/// The bytes are expected to be a domain-separated digest computed by the
/// producer. This type checks only that the value is nonzero; it neither
/// recomputes nor authenticates the digest.
#[derive(Clone, Copy, Eq, Hash, PartialEq)]
pub struct KfdTargetDebugTelemetryDigestV1([u8; 32]);

impl KfdTargetDebugTelemetryDigestV1 {
    pub fn from_bytes(bytes: [u8; 32]) -> Result<Self, KfdTargetDebugTelemetryDataErrorV1> {
        if bytes == [0; 32] {
            return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroDigest);
        }
        Ok(Self(bytes))
    }

    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for KfdTargetDebugTelemetryDigestV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("KfdTargetDebugTelemetryDigestV1(")?;
        write_hex(formatter, &self.0)?;
        formatter.write_str(")")
    }
}

/// Per-session correlation nonce generated by the debugger.
///
/// Callers should use an operating-system CSPRNG and a fresh value for every
/// target. Nonzero admission catches missing initialization only. The nonce is
/// sent in cleartext and supplies no cryptographic authentication.
#[derive(Clone, Copy, Eq, Hash, PartialEq)]
pub struct KfdTargetDebugSessionNonceV1([u8; 32]);

impl KfdTargetDebugSessionNonceV1 {
    pub fn from_bytes(bytes: [u8; 32]) -> Result<Self, KfdTargetDebugTelemetryDataErrorV1> {
        if bytes == [0; 32] {
            return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroNonce);
        }
        Ok(Self(bytes))
    }

    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for KfdTargetDebugSessionNonceV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("KfdTargetDebugSessionNonceV1(REDACTED)")
    }
}

/// Best-effort Linux process-instance binding for one telemetry peer.
///
/// The binding combines the PID visible in the receiver's PID namespace, its
/// `/proc` start-time tick, and effective Unix credentials. The receiver checks
/// packet `SCM_CREDENTIALS` and rechecks `/proc` while the peer remains visible.
/// A packet already queued when the peer exits is accepted only after its
/// kernel credentials, connected endpoint, nonce, and sequence all match. This
/// detects ordinary PID reuse while preserving the target's final queued
/// record. It is not a pidfd, a process-control capability, or proof about
/// namespaces not visible through this procfs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct KfdTargetDebugTelemetryProcessV1 {
    pid: u32,
    start_time_ticks: u64,
    effective_uid: u32,
    effective_gid: u32,
}

impl KfdTargetDebugTelemetryProcessV1 {
    /// Captures one currently live Linux process without granting authority to it.
    pub fn capture(pid: u32) -> Result<Self, KfdTargetDebugTelemetryProcessErrorV1> {
        if pid == 0 || i32::try_from(pid).is_err() {
            return Err(KfdTargetDebugTelemetryProcessErrorV1::InvalidPid);
        }
        let before = read_process_start_time(pid)?;
        let (effective_uid, effective_gid) = read_process_credentials(pid)?;
        let after = read_process_start_time(pid)?;
        if before != after {
            return Err(KfdTargetDebugTelemetryProcessErrorV1::IdentityChanged);
        }
        Ok(Self {
            pid,
            start_time_ticks: before,
            effective_uid,
            effective_gid,
        })
    }

    pub const fn pid(self) -> u32 {
        self.pid
    }

    pub const fn start_time_ticks(self) -> u64 {
        self.start_time_ticks
    }

    pub const fn effective_uid(self) -> u32 {
        self.effective_uid
    }

    pub const fn effective_gid(self) -> u32 {
        self.effective_gid
    }

    /// Opaque V2 correlation identity for this exact process occurrence.
    pub fn correlation_identity_v2(
        self,
    ) -> Result<KfdTargetDebugTelemetryDigestV1, KfdTargetDebugTelemetryDataErrorV1> {
        let mut digest = Sha256::new();
        digest.update(b"fe2o3-kfd-target-process-instance-v2\0");
        digest.update(self.pid.to_le_bytes());
        digest.update(self.start_time_ticks.to_le_bytes());
        digest.update(self.effective_uid.to_le_bytes());
        digest.update(self.effective_gid.to_le_bytes());
        KfdTargetDebugTelemetryDigestV1::from_bytes(digest.finalize().into())
    }

    pub(super) fn validate_current(self) -> Result<(), KfdTargetDebugTelemetryProcessErrorV1> {
        if Self::capture(self.pid)? != self {
            return Err(KfdTargetDebugTelemetryProcessErrorV1::IdentityChanged);
        }
        Ok(())
    }

    pub(super) fn validate_after_authenticated_packet(
        self,
    ) -> Result<(), KfdTargetDebugTelemetryProcessErrorV1> {
        match self.validate_current() {
            Err(KfdTargetDebugTelemetryProcessErrorV1::ProcIo { source, .. })
                if source.kind() == std::io::ErrorKind::NotFound =>
            {
                // SCM_CREDENTIALS describes the sender at send time. A seqpacket may remain
                // queued after that process exits, and the connected inherited endpoint plus
                // session nonce still identify the session. Every other procfs failure remains
                // fail-closed.
                Ok(())
            }
            result => result,
        }
    }

    pub(super) fn matches_credentials(self, pid: i32, uid: u32, gid: u32) -> bool {
        u32::try_from(pid).ok() == Some(self.pid)
            && uid == self.effective_uid
            && gid == self.effective_gid
    }
}

/// Creates a close-on-exec connected channel for provisioning across a target exec.
///
/// The caller retains the debugger descriptor and deliberately exposes only
/// the target descriptor across exec. Clearing close-on-exec and assigning a
/// child ABI descriptor are intentionally owned by the process launcher. The
/// returned descriptors are telemetry-only sockets and contain no KFD handle.
pub fn create_kfd_target_debug_telemetry_channel_v1()
-> Result<(OwnedFd, OwnedFd), KfdTargetDebugTelemetryTransportErrorV1> {
    socketpair(
        AddressFamily::UNIX,
        SocketType::SEQPACKET,
        SocketFlags::CLOEXEC,
        None,
    )
    .map_err(KfdTargetDebugTelemetryTransportErrorV1::CreateChannel)
}

/// Admits the telemetry endpoint deliberately inherited by `fe2o3-debug live-kfd`.
///
/// All three ABI variables must be absent or present together. The inherited
/// descriptor is duplicated atomically with close-on-exec before validation
/// and is never closed by this helper, so hostile environment input cannot make
/// the process close an unrelated descriptor. Only after the duplicate passes
/// endpoint and debugger-credential admission is the inherited original marked
/// close-on-exec. The environment is not mutated; callers may invoke this from
/// a multithreaded process, and stale text alone grants no socket authority.
pub fn admit_inherited_kfd_target_debug_telemetry_v1()
-> Result<Option<KfdCooperativeTargetTelemetryEndpointV1>, KfdInheritedTargetDebugTelemetryErrorV1>
{
    let descriptor = std::env::var_os(KFD_TARGET_DEBUG_TELEMETRY_FD_ENV_V1);
    let nonce = std::env::var_os(KFD_TARGET_DEBUG_TELEMETRY_NONCE_ENV_V1);
    let debugger = std::env::var_os(KFD_TARGET_DEBUG_TELEMETRY_DEBUGGER_PID_ENV_V1);
    if descriptor.is_none() && nonce.is_none() && debugger.is_none() {
        return Ok(None);
    }
    let (descriptor, nonce, debugger) = match (descriptor, nonce, debugger) {
        (Some(descriptor), Some(nonce), Some(debugger)) => (descriptor, nonce, debugger),
        _ => return Err(KfdInheritedTargetDebugTelemetryErrorV1::IncompleteEnvironment),
    };
    let descriptor = descriptor
        .to_str()
        .and_then(decode_canonical_decimal_v1::<i32>)
        .filter(|value| *value >= 3)
        .ok_or(KfdInheritedTargetDebugTelemetryErrorV1::InvalidDescriptor)?;
    let nonce = nonce
        .to_str()
        .and_then(decode_nonce_hex_v1)
        .ok_or(KfdInheritedTargetDebugTelemetryErrorV1::InvalidNonce)
        .and_then(|bytes| {
            KfdTargetDebugSessionNonceV1::from_bytes(bytes)
                .map_err(|_| KfdInheritedTargetDebugTelemetryErrorV1::InvalidNonce)
        })?;
    let debugger = debugger
        .to_str()
        .and_then(decode_canonical_decimal_v1::<u32>)
        .ok_or(KfdInheritedTargetDebugTelemetryErrorV1::InvalidDebuggerProcess)
        .and_then(|pid| {
            KfdTargetDebugTelemetryProcessV1::capture(pid)
                .map_err(KfdInheritedTargetDebugTelemetryErrorV1::DebuggerProcess)
        })?;
    let endpoint = duplicate_raw_descriptor_cloexec_v1(descriptor)
        .map_err(KfdInheritedTargetDebugTelemetryErrorV1::DuplicateDescriptor)?;
    let endpoint = KfdCooperativeTargetTelemetryEndpointV1::admit(endpoint, nonce, debugger)
        .map_err(KfdInheritedTargetDebugTelemetryErrorV1::Admit)?;
    protect_raw_descriptor_v1(descriptor)
        .map_err(KfdInheritedTargetDebugTelemetryErrorV1::ProtectDescriptor)?;
    Ok(Some(endpoint))
}

pub(super) fn decode_nonce_hex_v1(value: &str) -> Option<[u8; 32]> {
    if value.len() != 64
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
    {
        return None;
    }
    let mut output = [0_u8; 32];
    for (index, pair) in value.as_bytes().chunks_exact(2).enumerate() {
        let high = decode_lower_hex_digit_v1(pair[0])?;
        let low = decode_lower_hex_digit_v1(pair[1])?;
        output[index] = high << 4 | low;
    }
    Some(output)
}

pub(super) fn decode_canonical_decimal_v1<T: std::str::FromStr>(value: &str) -> Option<T> {
    if !value
        .as_bytes()
        .first()
        .is_some_and(|byte| matches!(byte, b'1'..=b'9'))
        || !value.bytes().all(|byte| byte.is_ascii_digit())
    {
        return None;
    }
    value.parse().ok()
}

pub(super) fn duplicate_raw_descriptor_cloexec_v1(
    descriptor: i32,
) -> Result<OwnedFd, rustix::io::Errno> {
    // SAFETY: fcntl treats the scalar as an index into the calling process's descriptor table.
    // It returns EBADF for an invalid or concurrently closed entry. Only a distinct nonnegative
    // descriptor returned by F_DUPFD_CLOEXEC is converted into Rust ownership.
    let duplicate = unsafe { libc::fcntl(descriptor, libc::F_DUPFD_CLOEXEC, 3) };
    if duplicate < 0 {
        return Err(last_errno_v1());
    }
    // SAFETY: successful F_DUPFD_CLOEXEC returned a fresh descriptor not owned elsewhere.
    Ok(unsafe { OwnedFd::from_raw_fd(duplicate) })
}

pub(super) fn protect_raw_descriptor_v1(descriptor: i32) -> Result<(), rustix::io::Errno> {
    // SAFETY: F_GETFD consumes only the scalar descriptor number and returns EBADF when it is no
    // longer valid. No Rust ownership is constructed for the inherited descriptor.
    let flags = unsafe { libc::fcntl(descriptor, libc::F_GETFD) };
    if flags < 0 {
        return Err(last_errno_v1());
    }
    // SAFETY: F_SETFD changes only the descriptor flags for this scalar table entry.
    if unsafe { libc::fcntl(descriptor, libc::F_SETFD, flags | libc::FD_CLOEXEC) } < 0 {
        return Err(last_errno_v1());
    }
    Ok(())
}

fn last_errno_v1() -> rustix::io::Errno {
    rustix::io::Errno::from_raw_os_error(
        std::io::Error::last_os_error()
            .raw_os_error()
            .unwrap_or(libc::EIO),
    )
}

fn decode_lower_hex_digit_v1(value: u8) -> Option<u8> {
    match value {
        b'0'..=b'9' => Some(value - b'0'),
        b'a'..=b'f' => Some(value - b'a' + 10),
        _ => None,
    }
}

/// One canonical target-declared artifact identity and exact byte length.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct KfdTargetDebugArtifactIdentityV1 {
    digest: KfdTargetDebugTelemetryDigestV1,
    byte_length: u64,
}

impl KfdTargetDebugArtifactIdentityV1 {
    pub fn new(
        digest: KfdTargetDebugTelemetryDigestV1,
        byte_length: u64,
    ) -> Result<Self, KfdTargetDebugTelemetryDataErrorV1> {
        if byte_length == 0 {
            return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroLength);
        }
        Ok(Self {
            digest,
            byte_length,
        })
    }

    pub const fn digest(self) -> KfdTargetDebugTelemetryDigestV1 {
        self.digest
    }

    pub const fn byte_length(self) -> u64 {
        self.byte_length
    }
}

/// Stable logical role of a target-declared artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugArtifactRoleV1 {
    ApplicationExecutable = 1,
    SimulationBundleV2 = 2,
    SimulationRequest = 3,
    KernelIr = 4,
    SourceMapV2 = 5,
    CodeObject = 6,
    KernelArguments = 7,
    DebugSidecar = 8,
}

impl KfdTargetDebugArtifactRoleV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::ApplicationExecutable),
            2 => Ok(Self::SimulationBundleV2),
            3 => Ok(Self::SimulationRequest),
            4 => Ok(Self::KernelIr),
            5 => Ok(Self::SourceMapV2),
            6 => Ok(Self::CodeObject),
            7 => Ok(Self::KernelArguments),
            8 => Ok(Self::DebugSidecar),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "artifact role",
                value,
            }),
        }
    }
}

/// Target-declared dispatch lifecycle phase.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugDispatchPhaseV1 {
    Prepared = 1,
    Submitted = 2,
    Completed = 3,
    Failed = 4,
    Cancelled = 5,
}

impl KfdTargetDebugDispatchPhaseV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::Prepared),
            2 => Ok(Self::Submitted),
            3 => Ok(Self::Completed),
            4 => Ok(Self::Failed),
            5 => Ok(Self::Cancelled),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "dispatch phase",
                value,
            }),
        }
    }
}

/// Target-declared allocation lifecycle phase.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugAllocationPhaseV1 {
    Created = 1,
    Released = 2,
}

impl KfdTargetDebugAllocationPhaseV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::Created),
            2 => Ok(Self::Released),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "allocation phase",
                value,
            }),
        }
    }
}

/// Logical allocation memory class. This does not expose or prove a native allocation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugMemoryKindV1 {
    HostVisible = 1,
    DeviceLocal = 2,
    Shared = 3,
    KernelArguments = 4,
    QueueStorage = 5,
}

impl KfdTargetDebugMemoryKindV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::HostVisible),
            2 => Ok(Self::DeviceLocal),
            3 => Ok(Self::Shared),
            4 => Ok(Self::KernelArguments),
            5 => Ok(Self::QueueStorage),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "memory kind",
                value,
            }),
        }
    }
}

/// Declared logical access policy for an allocation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugMemoryAccessV1 {
    ReadOnly = 1,
    WriteOnly = 2,
    ReadWrite = 3,
}

impl KfdTargetDebugMemoryAccessV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::ReadOnly),
            2 => Ok(Self::WriteOnly),
            3 => Ok(Self::ReadWrite),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "memory access",
                value,
            }),
        }
    }
}

/// Severity of one target-declared diagnostic identity.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugDiagnosticSeverityV1 {
    Note = 1,
    Warning = 2,
    Error = 3,
    Fatal = 4,
}

impl KfdTargetDebugDiagnosticSeverityV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::Note),
            2 => Ok(Self::Warning),
            3 => Ok(Self::Error),
            4 => Ok(Self::Fatal),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "diagnostic severity",
                value,
            }),
        }
    }
}

/// Target-declared session outcome.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u16)]
pub enum KfdTargetDebugSessionOutcomeV1 {
    Completed = 1,
    Failed = 2,
    Cancelled = 3,
}

impl KfdTargetDebugSessionOutcomeV1 {
    fn from_wire(value: u16) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        match value {
            1 => Ok(Self::Completed),
            2 => Ok(Self::Failed),
            3 => Ok(Self::Cancelled),
            _ => Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidEnum {
                field: "session outcome",
                value,
            }),
        }
    }
}

/// Versioned cooperative target payload.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum KfdTargetDebugTelemetryPayloadV1 {
    SessionStarted {
        process_instance: KfdTargetDebugTelemetryDigestV1,
        executable: KfdTargetDebugArtifactIdentityV1,
    },
    Artifact {
        role: KfdTargetDebugArtifactRoleV1,
        ordinal: u32,
        artifact: KfdTargetDebugArtifactIdentityV1,
    },
    Dispatch {
        phase: KfdTargetDebugDispatchPhaseV1,
        dispatch: KfdTargetDebugTelemetryDigestV1,
        kernel: KfdTargetDebugTelemetryDigestV1,
        code_object: KfdTargetDebugTelemetryDigestV1,
        logical_queue: KfdTargetDebugTelemetryDigestV1,
        grid: [u32; 3],
        workgroup: [u32; 3],
        dynamic_shared_memory_bytes: u32,
    },
    Allocation {
        phase: KfdTargetDebugAllocationPhaseV1,
        memory_kind: KfdTargetDebugMemoryKindV1,
        access: KfdTargetDebugMemoryAccessV1,
        allocation: KfdTargetDebugTelemetryDigestV1,
        logical_scope: KfdTargetDebugTelemetryDigestV1,
        byte_length: u64,
        alignment: u64,
    },
    Diagnostic {
        severity: KfdTargetDebugDiagnosticSeverityV1,
        stable_code: u32,
        diagnostic: KfdTargetDebugTelemetryDigestV1,
        logical_scope: KfdTargetDebugTelemetryDigestV1,
    },
    SessionEnded {
        outcome: KfdTargetDebugSessionOutcomeV1,
    },
}

impl KfdTargetDebugTelemetryPayloadV1 {
    /// Validates cross-field constraints that are not represented by the field types.
    pub fn validate(&self) -> Result<(), KfdTargetDebugTelemetryDataErrorV1> {
        match self {
            Self::Dispatch {
                grid, workgroup, ..
            } => {
                for axis in 0..3 {
                    if grid[axis] == 0 || workgroup[axis] == 0 {
                        return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroDimension { axis });
                    }
                    if workgroup[axis] > grid[axis] {
                        return Err(KfdTargetDebugTelemetryDataErrorV1::WorkgroupExceedsGrid {
                            axis,
                            grid: grid[axis],
                            workgroup: workgroup[axis],
                        });
                    }
                }
            }
            Self::Allocation {
                byte_length,
                alignment,
                ..
            } => {
                if *byte_length == 0 {
                    return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroLength);
                }
                if *alignment == 0 || !alignment.is_power_of_two() {
                    return Err(KfdTargetDebugTelemetryDataErrorV1::InvalidAlignment(
                        *alignment,
                    ));
                }
            }
            Self::Diagnostic { stable_code, .. } if *stable_code == 0 => {
                return Err(KfdTargetDebugTelemetryDataErrorV1::ZeroDiagnosticCode);
            }
            _ => {}
        }
        Ok(())
    }

    fn wire_kind(&self) -> u16 {
        match self {
            Self::SessionStarted { .. } => 1,
            Self::Artifact { .. } => 2,
            Self::Dispatch { .. } => 3,
            Self::Allocation { .. } => 4,
            Self::Diagnostic { .. } => 5,
            Self::SessionEnded { .. } => 6,
        }
    }

    fn encode_payload(&self, output: &mut [u8; PAYLOAD_CAPACITY_V1]) -> usize {
        match self {
            Self::SessionStarted {
                process_instance,
                executable,
            } => {
                output[..32].copy_from_slice(process_instance.as_bytes());
                output[32..64].copy_from_slice(executable.digest().as_bytes());
                output[64..72].copy_from_slice(&executable.byte_length().to_le_bytes());
                72
            }
            Self::Artifact {
                role,
                ordinal,
                artifact,
            } => {
                output[..2].copy_from_slice(&(*role as u16).to_le_bytes());
                output[4..8].copy_from_slice(&ordinal.to_le_bytes());
                output[8..40].copy_from_slice(artifact.digest().as_bytes());
                output[40..48].copy_from_slice(&artifact.byte_length().to_le_bytes());
                48
            }
            Self::Dispatch {
                phase,
                dispatch,
                kernel,
                code_object,
                logical_queue,
                grid,
                workgroup,
                dynamic_shared_memory_bytes,
            } => {
                output[..2].copy_from_slice(&(*phase as u16).to_le_bytes());
                put_u32_triplet(&mut output[4..16], *grid);
                put_u32_triplet(&mut output[16..28], *workgroup);
                output[28..32].copy_from_slice(&dynamic_shared_memory_bytes.to_le_bytes());
                output[32..64].copy_from_slice(dispatch.as_bytes());
                output[64..96].copy_from_slice(kernel.as_bytes());
                output[96..128].copy_from_slice(code_object.as_bytes());
                output[128..160].copy_from_slice(logical_queue.as_bytes());
                160
            }
            Self::Allocation {
                phase,
                memory_kind,
                access,
                allocation,
                logical_scope,
                byte_length,
                alignment,
            } => {
                output[..2].copy_from_slice(&(*phase as u16).to_le_bytes());
                output[2..4].copy_from_slice(&(*memory_kind as u16).to_le_bytes());
                output[4..6].copy_from_slice(&(*access as u16).to_le_bytes());
                output[8..16].copy_from_slice(&byte_length.to_le_bytes());
                output[16..24].copy_from_slice(&alignment.to_le_bytes());
                output[24..56].copy_from_slice(allocation.as_bytes());
                output[56..88].copy_from_slice(logical_scope.as_bytes());
                88
            }
            Self::Diagnostic {
                severity,
                stable_code,
                diagnostic,
                logical_scope,
            } => {
                output[..2].copy_from_slice(&(*severity as u16).to_le_bytes());
                output[4..8].copy_from_slice(&stable_code.to_le_bytes());
                output[8..40].copy_from_slice(diagnostic.as_bytes());
                output[40..72].copy_from_slice(logical_scope.as_bytes());
                72
            }
            Self::SessionEnded { outcome } => {
                output[..2].copy_from_slice(&(*outcome as u16).to_le_bytes());
                2
            }
        }
    }

    fn decode_payload(
        kind: u16,
        bytes: &[u8],
    ) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        let payload = match kind {
            1 => {
                require_payload_len(bytes, 72)?;
                Self::SessionStarted {
                    process_instance: decode_digest(&bytes[..32])?,
                    executable: decode_artifact(&bytes[32..64], &bytes[64..72])?,
                }
            }
            2 => {
                require_payload_len(bytes, 48)?;
                require_zero("artifact reserved", &bytes[2..4])?;
                Self::Artifact {
                    role: KfdTargetDebugArtifactRoleV1::from_wire(read_u16(&bytes[..2]))?,
                    ordinal: read_u32(&bytes[4..8]),
                    artifact: decode_artifact(&bytes[8..40], &bytes[40..48])?,
                }
            }
            3 => {
                require_payload_len(bytes, 160)?;
                require_zero("dispatch reserved", &bytes[2..4])?;
                Self::Dispatch {
                    phase: KfdTargetDebugDispatchPhaseV1::from_wire(read_u16(&bytes[..2]))?,
                    grid: read_u32_triplet(&bytes[4..16]),
                    workgroup: read_u32_triplet(&bytes[16..28]),
                    dynamic_shared_memory_bytes: read_u32(&bytes[28..32]),
                    dispatch: decode_digest(&bytes[32..64])?,
                    kernel: decode_digest(&bytes[64..96])?,
                    code_object: decode_digest(&bytes[96..128])?,
                    logical_queue: decode_digest(&bytes[128..160])?,
                }
            }
            4 => {
                require_payload_len(bytes, 88)?;
                require_zero("allocation reserved", &bytes[6..8])?;
                Self::Allocation {
                    phase: KfdTargetDebugAllocationPhaseV1::from_wire(read_u16(&bytes[..2]))?,
                    memory_kind: KfdTargetDebugMemoryKindV1::from_wire(read_u16(&bytes[2..4]))?,
                    access: KfdTargetDebugMemoryAccessV1::from_wire(read_u16(&bytes[4..6]))?,
                    byte_length: read_u64(&bytes[8..16]),
                    alignment: read_u64(&bytes[16..24]),
                    allocation: decode_digest(&bytes[24..56])?,
                    logical_scope: decode_digest(&bytes[56..88])?,
                }
            }
            5 => {
                require_payload_len(bytes, 72)?;
                require_zero("diagnostic reserved", &bytes[2..4])?;
                Self::Diagnostic {
                    severity: KfdTargetDebugDiagnosticSeverityV1::from_wire(read_u16(&bytes[..2]))?,
                    stable_code: read_u32(&bytes[4..8]),
                    diagnostic: decode_digest(&bytes[8..40])?,
                    logical_scope: decode_digest(&bytes[40..72])?,
                }
            }
            6 => {
                require_payload_len(bytes, 2)?;
                Self::SessionEnded {
                    outcome: KfdTargetDebugSessionOutcomeV1::from_wire(read_u16(bytes))?,
                }
            }
            _ => return Err(KfdTargetDebugTelemetryProtocolErrorV1::UnknownKind(kind)),
        };
        payload
            .validate()
            .map_err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayload)?;
        Ok(payload)
    }
}

/// One decoded canonical telemetry record.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct KfdTargetDebugTelemetryRecordV1 {
    sequence: u64,
    session_nonce: KfdTargetDebugSessionNonceV1,
    payload: KfdTargetDebugTelemetryPayloadV1,
}

impl KfdTargetDebugTelemetryRecordV1 {
    pub fn new(
        sequence: u64,
        session_nonce: KfdTargetDebugSessionNonceV1,
        payload: KfdTargetDebugTelemetryPayloadV1,
    ) -> Result<Self, KfdTargetDebugTelemetryDataErrorV1> {
        payload.validate()?;
        Ok(Self {
            sequence,
            session_nonce,
            payload,
        })
    }

    pub const fn sequence(&self) -> u64 {
        self.sequence
    }

    pub const fn session_nonce(&self) -> KfdTargetDebugSessionNonceV1 {
        self.session_nonce
    }

    pub const fn payload(&self) -> &KfdTargetDebugTelemetryPayloadV1 {
        &self.payload
    }

    /// Serializes one record into a fully initialized canonical wire packet.
    pub fn to_wire_bytes(&self) -> [u8; KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1] {
        let mut bytes = [0_u8; KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1];
        bytes[..8].copy_from_slice(&MAGIC_V1);
        bytes[8..10].copy_from_slice(&VERSION_V1.to_le_bytes());
        bytes[10..12].copy_from_slice(&self.payload.wire_kind().to_le_bytes());
        bytes[16..24].copy_from_slice(&self.sequence.to_le_bytes());
        bytes[24..56].copy_from_slice(self.session_nonce.as_bytes());
        let mut payload = [0_u8; PAYLOAD_CAPACITY_V1];
        let payload_len = self.payload.encode_payload(&mut payload);
        bytes[12..16].copy_from_slice(&(payload_len as u32).to_le_bytes());
        bytes[HEADER_LEN_V1..CHECKSUM_OFFSET_V1].copy_from_slice(&payload);
        let checksum = checksum(&bytes[..CHECKSUM_OFFSET_V1]);
        bytes[CHECKSUM_OFFSET_V1..].copy_from_slice(&checksum);
        bytes
    }

    /// Decodes one exact packet and rejects noncanonical reserved or padding bytes.
    pub fn from_wire_bytes(bytes: &[u8]) -> Result<Self, KfdTargetDebugTelemetryProtocolErrorV1> {
        if bytes.len() != KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1 {
            return Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidWireLength {
                expected: KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1,
                actual: bytes.len(),
            });
        }
        if bytes[..8] != MAGIC_V1 {
            return Err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidMagic);
        }
        let version = read_u16(&bytes[8..10]);
        if version != VERSION_V1 {
            return Err(KfdTargetDebugTelemetryProtocolErrorV1::UnsupportedVersion(
                version,
            ));
        }
        let payload_len = usize::try_from(read_u32(&bytes[12..16])).map_err(|_| {
            KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayloadLength {
                capacity: PAYLOAD_CAPACITY_V1,
                actual: usize::MAX,
            }
        })?;
        if payload_len > PAYLOAD_CAPACITY_V1 {
            return Err(
                KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayloadLength {
                    capacity: PAYLOAD_CAPACITY_V1,
                    actual: payload_len,
                },
            );
        }
        let expected = checksum(&bytes[..CHECKSUM_OFFSET_V1]);
        if bytes[CHECKSUM_OFFSET_V1..] != expected {
            return Err(KfdTargetDebugTelemetryProtocolErrorV1::ChecksumMismatch);
        }
        require_zero(
            "payload padding",
            &bytes[HEADER_LEN_V1 + payload_len..CHECKSUM_OFFSET_V1],
        )?;
        let session_nonce = KfdTargetDebugSessionNonceV1::from_bytes(
            bytes[24..56].try_into().expect("fixed nonce slice"),
        )
        .map_err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayload)?;
        let payload = KfdTargetDebugTelemetryPayloadV1::decode_payload(
            read_u16(&bytes[10..12]),
            &bytes[HEADER_LEN_V1..HEADER_LEN_V1 + payload_len],
        )?;
        Ok(Self {
            sequence: read_u64(&bytes[16..24]),
            session_nonce,
            payload,
        })
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum TelemetryLifecycleV1 {
    AwaitingStart,
    Active,
    Finished,
}

/// Debugger-side receiver for one cooperative target session.
///
/// Every packet must carry kernel-supplied Linux credentials for the captured
/// target process. A successfully consumed protocol violation poisons this
/// endpoint because sequence and lifecycle recovery would be ambiguous.
pub struct KfdDebuggerTelemetryEndpointV1 {
    endpoint: OwnedFd,
    nonce: KfdTargetDebugSessionNonceV1,
    target: KfdTargetDebugTelemetryProcessV1,
    next_sequence: u64,
    lifecycle: TelemetryLifecycleV1,
    poisoned: bool,
}

impl fmt::Debug for KfdDebuggerTelemetryEndpointV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("KfdDebuggerTelemetryEndpointV1")
            .field("target", &self.target)
            .field("next_sequence", &self.next_sequence)
            .field("lifecycle", &self.lifecycle)
            .field("poisoned", &self.poisoned)
            .field("authority", &"telemetry-only")
            .finish_non_exhaustive()
    }
}

impl KfdDebuggerTelemetryEndpointV1 {
    pub fn admit(
        endpoint: OwnedFd,
        nonce: KfdTargetDebugSessionNonceV1,
        target: KfdTargetDebugTelemetryProcessV1,
    ) -> Result<Self, KfdTargetDebugTelemetryTransportErrorV1> {
        target.validate_current()?;
        validate_connected_seqpacket(&endpoint)?;
        set_socket_passcred(&endpoint, true)
            .map_err(KfdTargetDebugTelemetryTransportErrorV1::ConfigureCredentials)?;
        if !socket_passcred(&endpoint)
            .map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?
        {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::CredentialsDisabled);
        }
        Ok(Self {
            endpoint,
            nonce,
            target,
            next_sequence: 0,
            lifecycle: TelemetryLifecycleV1::AwaitingStart,
            poisoned: false,
        })
    }

    /// Receives the next record, blocking until a packet or EOF is available.
    pub fn receive(
        &mut self,
    ) -> Result<KfdTargetDebugTelemetryRecordV1, KfdTargetDebugTelemetryTransportErrorV1> {
        self.receive_inner(RecvFlags::CMSG_CLOEXEC)?
            .ok_or(KfdTargetDebugTelemetryTransportErrorV1::EndpointNotReady)
    }

    /// Receives one immediately available record without blocking.
    pub fn try_receive(
        &mut self,
    ) -> Result<Option<KfdTargetDebugTelemetryRecordV1>, KfdTargetDebugTelemetryTransportErrorV1>
    {
        self.receive_inner(RecvFlags::CMSG_CLOEXEC | RecvFlags::DONTWAIT)
    }

    pub const fn is_finished(&self) -> bool {
        matches!(self.lifecycle, TelemetryLifecycleV1::Finished)
    }

    fn receive_inner(
        &mut self,
        flags: RecvFlags,
    ) -> Result<Option<KfdTargetDebugTelemetryRecordV1>, KfdTargetDebugTelemetryTransportErrorV1>
    {
        if self.poisoned {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::Poisoned);
        }
        if self.is_finished() {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::SessionFinished);
        }
        let received = receive_packet(&self.endpoint, flags, self.target);
        let bytes = match received {
            Ok(Some(bytes)) => bytes,
            Ok(None) => return Ok(None),
            Err(error) => {
                self.poisoned = true;
                return Err(error);
            }
        };
        let record = match KfdTargetDebugTelemetryRecordV1::from_wire_bytes(&bytes) {
            Ok(record) => record,
            Err(error) => {
                self.poisoned = true;
                return Err(error.into());
            }
        };
        if record.session_nonce != self.nonce {
            self.poisoned = true;
            return Err(KfdTargetDebugTelemetryTransportErrorV1::NonceMismatch);
        }
        if record.sequence != self.next_sequence {
            self.poisoned = true;
            return Err(KfdTargetDebugTelemetryTransportErrorV1::SequenceMismatch {
                expected: self.next_sequence,
                actual: record.sequence,
            });
        }
        if let Err(error) = admit_lifecycle(self.lifecycle, &record.payload) {
            self.poisoned = true;
            return Err(error.into());
        }
        self.next_sequence = self.next_sequence.checked_add(1).ok_or_else(|| {
            self.poisoned = true;
            KfdTargetDebugTelemetryTransportErrorV1::SequenceExhausted
        })?;
        self.lifecycle = next_lifecycle(self.lifecycle, &record.payload);
        Ok(Some(record))
    }
}

/// Cooperative target-side sender for one debugger session.
///
/// The target endpoint validates the connected debugger credentials captured
/// at channel provisioning time. It sends declarations only and accepts no
/// commands, preventing this telemetry path from becoming an authority grant.
pub struct KfdCooperativeTargetTelemetryEndpointV1 {
    endpoint: OwnedFd,
    nonce: KfdTargetDebugSessionNonceV1,
    debugger: KfdTargetDebugTelemetryProcessV1,
    next_sequence: u64,
    lifecycle: TelemetryLifecycleV1,
    poisoned: bool,
}

impl fmt::Debug for KfdCooperativeTargetTelemetryEndpointV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("KfdCooperativeTargetTelemetryEndpointV1")
            .field("debugger", &self.debugger)
            .field("next_sequence", &self.next_sequence)
            .field("lifecycle", &self.lifecycle)
            .field("poisoned", &self.poisoned)
            .field("authority", &"telemetry-only")
            .finish_non_exhaustive()
    }
}

impl KfdCooperativeTargetTelemetryEndpointV1 {
    pub fn admit(
        endpoint: OwnedFd,
        nonce: KfdTargetDebugSessionNonceV1,
        debugger: KfdTargetDebugTelemetryProcessV1,
    ) -> Result<Self, KfdTargetDebugTelemetryTransportErrorV1> {
        debugger.validate_current()?;
        validate_connected_seqpacket(&endpoint)?;
        let peer = socket_peercred(&endpoint)
            .map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?;
        if !debugger.matches_credentials(
            peer.pid.as_raw_pid(),
            peer.uid.as_raw(),
            peer.gid.as_raw(),
        ) {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::PeerCredentialMismatch);
        }
        Ok(Self {
            endpoint,
            nonce,
            debugger,
            next_sequence: 0,
            lifecycle: TelemetryLifecycleV1::AwaitingStart,
            poisoned: false,
        })
    }

    /// Sends one declaration with the endpoint-owned nonce and sequence number.
    pub fn send(
        &mut self,
        payload: KfdTargetDebugTelemetryPayloadV1,
    ) -> Result<KfdTargetDebugTelemetryRecordV1, KfdTargetDebugTelemetryTransportErrorV1> {
        if self.poisoned {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::Poisoned);
        }
        if self.lifecycle == TelemetryLifecycleV1::Finished {
            return Err(KfdTargetDebugTelemetryTransportErrorV1::SessionFinished);
        }
        payload.validate()?;
        admit_lifecycle(self.lifecycle, &payload)?;
        self.debugger.validate_current()?;
        let record = KfdTargetDebugTelemetryRecordV1::new(self.next_sequence, self.nonce, payload)?;
        let bytes = record.to_wire_bytes();
        loop {
            match send(&self.endpoint, &bytes, SendFlags::NOSIGNAL) {
                Ok(actual) if actual == bytes.len() => break,
                Ok(actual) => {
                    self.poisoned = true;
                    return Err(KfdTargetDebugTelemetryTransportErrorV1::PartialSend {
                        expected: bytes.len(),
                        actual,
                    });
                }
                Err(rustix::io::Errno::INTR) => continue,
                Err(error) => {
                    self.poisoned = true;
                    return Err(KfdTargetDebugTelemetryTransportErrorV1::Send(error));
                }
            }
        }
        self.next_sequence = self.next_sequence.checked_add(1).ok_or_else(|| {
            self.poisoned = true;
            KfdTargetDebugTelemetryTransportErrorV1::SequenceExhausted
        })?;
        self.lifecycle = next_lifecycle(self.lifecycle, &record.payload);
        Ok(record)
    }

    pub const fn is_finished(&self) -> bool {
        matches!(self.lifecycle, TelemetryLifecycleV1::Finished)
    }
}

pub(super) fn validate_connected_seqpacket(
    endpoint: &OwnedFd,
) -> Result<(), KfdTargetDebugTelemetryTransportErrorV1> {
    let domain =
        socket_domain(endpoint).map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?;
    if domain != AddressFamily::UNIX {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::WrongSocketDomain);
    }
    let kind =
        socket_type(endpoint).map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?;
    if kind != SocketType::SEQPACKET {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::WrongSocketType);
    }
    if getpeername(endpoint)
        .map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?
        .is_none()
    {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::UnconnectedSocket);
    }
    socket_peercred(endpoint).map_err(KfdTargetDebugTelemetryTransportErrorV1::InspectSocket)?;
    Ok(())
}

fn receive_packet(
    endpoint: &OwnedFd,
    flags: RecvFlags,
    target: KfdTargetDebugTelemetryProcessV1,
) -> Result<
    Option<[u8; KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1]>,
    KfdTargetDebugTelemetryTransportErrorV1,
> {
    let mut bytes = [0_u8; KFD_TARGET_DEBUG_TELEMETRY_WIRE_LEN_V1];
    let mut control_storage =
        [MaybeUninit::uninit(); rustix::cmsg_space!(ScmCredentials(1), ScmRights(4))];
    let mut control = RecvAncillaryBuffer::new(&mut control_storage);
    let mut vectors = [IoSliceMut::new(&mut bytes)];
    let message = loop {
        match recvmsg(endpoint, &mut vectors, &mut control, flags) {
            Ok(message) => break message,
            Err(rustix::io::Errno::INTR) => continue,
            Err(rustix::io::Errno::AGAIN) if flags.contains(RecvFlags::DONTWAIT) => {
                return Ok(None);
            }
            Err(error) => return Err(KfdTargetDebugTelemetryTransportErrorV1::Receive(error)),
        }
    };
    let mut credentials = None;
    let mut forbidden_ancillary = false;
    for item in control.drain() {
        match item {
            RecvAncillaryMessage::ScmCredentials(value) => {
                if credentials.replace(value).is_some() {
                    forbidden_ancillary = true;
                }
            }
            RecvAncillaryMessage::ScmRights(rights) => {
                drop(rights);
                forbidden_ancillary = true;
            }
            _ => forbidden_ancillary = true,
        }
    }
    if message.flags.contains(ReturnFlags::TRUNC) {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::PacketTruncated);
    }
    if message.flags.contains(ReturnFlags::CTRUNC) {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::AncillaryDataTruncated);
    }
    if forbidden_ancillary {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::ForbiddenAncillaryData);
    }
    if message.bytes == 0 {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::UnexpectedEof);
    }
    if message.bytes != bytes.len() {
        return Err(
            KfdTargetDebugTelemetryTransportErrorV1::InvalidPacketLength {
                expected: bytes.len(),
                actual: message.bytes,
            },
        );
    }
    let credentials =
        credentials.ok_or(KfdTargetDebugTelemetryTransportErrorV1::MissingPeerCredentials)?;
    if !target.matches_credentials(
        credentials.pid.as_raw_pid(),
        credentials.uid.as_raw(),
        credentials.gid.as_raw(),
    ) {
        return Err(KfdTargetDebugTelemetryTransportErrorV1::PeerCredentialMismatch);
    }
    target.validate_after_authenticated_packet()?;
    Ok(Some(bytes))
}

fn admit_lifecycle(
    lifecycle: TelemetryLifecycleV1,
    payload: &KfdTargetDebugTelemetryPayloadV1,
) -> Result<(), KfdTargetDebugTelemetryProtocolErrorV1> {
    match (lifecycle, payload) {
        (
            TelemetryLifecycleV1::AwaitingStart,
            KfdTargetDebugTelemetryPayloadV1::SessionStarted { .. },
        )
        | (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::Artifact { .. })
        | (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::Dispatch { .. })
        | (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::Allocation { .. })
        | (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::Diagnostic { .. })
        | (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::SessionEnded { .. }) => {
            Ok(())
        }
        (TelemetryLifecycleV1::Finished, _) => {
            Err(KfdTargetDebugTelemetryProtocolErrorV1::RecordAfterSessionEnd)
        }
        (TelemetryLifecycleV1::AwaitingStart, _) => {
            Err(KfdTargetDebugTelemetryProtocolErrorV1::MissingSessionStart)
        }
        (TelemetryLifecycleV1::Active, KfdTargetDebugTelemetryPayloadV1::SessionStarted { .. }) => {
            Err(KfdTargetDebugTelemetryProtocolErrorV1::DuplicateSessionStart)
        }
    }
}

fn next_lifecycle(
    current: TelemetryLifecycleV1,
    payload: &KfdTargetDebugTelemetryPayloadV1,
) -> TelemetryLifecycleV1 {
    match payload {
        KfdTargetDebugTelemetryPayloadV1::SessionStarted { .. } => TelemetryLifecycleV1::Active,
        KfdTargetDebugTelemetryPayloadV1::SessionEnded { .. } => TelemetryLifecycleV1::Finished,
        _ => current,
    }
}

fn read_process_start_time(pid: u32) -> Result<u64, KfdTargetDebugTelemetryProcessErrorV1> {
    let bytes =
        read_bounded_proc_file(format!("/proc/{pid}/stat"), MAX_PROC_STAT_BYTES_V1, "stat")?;
    let text = std::str::from_utf8(&bytes)
        .map_err(|_| KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)?;
    let close = text
        .rfind(')')
        .ok_or(KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)?;
    let open = text[..close]
        .find('(')
        .ok_or(KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)?;
    let observed_pid = text[..open]
        .trim()
        .parse::<u32>()
        .map_err(|_| KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)?;
    if observed_pid != pid {
        return Err(KfdTargetDebugTelemetryProcessErrorV1::IdentityChanged);
    }
    text[close + 1..]
        .split_whitespace()
        .nth(19)
        .ok_or(KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)?
        .parse()
        .map_err(|_| KfdTargetDebugTelemetryProcessErrorV1::MalformedStat)
}

fn read_process_credentials(pid: u32) -> Result<(u32, u32), KfdTargetDebugTelemetryProcessErrorV1> {
    let bytes = read_bounded_proc_file(
        format!("/proc/{pid}/status"),
        MAX_PROC_STATUS_BYTES_V1,
        "status",
    )?;
    let text = std::str::from_utf8(&bytes)
        .map_err(|_| KfdTargetDebugTelemetryProcessErrorV1::MalformedStatus)?;
    let uid = unique_effective_credential(text, "Uid:")?;
    let gid = unique_effective_credential(text, "Gid:")?;
    Ok((uid, gid))
}

fn unique_effective_credential(
    text: &str,
    field: &'static str,
) -> Result<u32, KfdTargetDebugTelemetryProcessErrorV1> {
    let mut matches = text.lines().filter(|line| line.starts_with(field));
    let line = matches
        .next()
        .ok_or(KfdTargetDebugTelemetryProcessErrorV1::MalformedStatus)?;
    if matches.next().is_some() {
        return Err(KfdTargetDebugTelemetryProcessErrorV1::MalformedStatus);
    }
    line[field.len()..]
        .split_whitespace()
        .nth(1)
        .ok_or(KfdTargetDebugTelemetryProcessErrorV1::MalformedStatus)?
        .parse()
        .map_err(|_| KfdTargetDebugTelemetryProcessErrorV1::MalformedStatus)
}

fn read_bounded_proc_file(
    path: String,
    limit: u64,
    operation: &'static str,
) -> Result<Vec<u8>, KfdTargetDebugTelemetryProcessErrorV1> {
    let file = File::open(path)
        .map_err(|source| KfdTargetDebugTelemetryProcessErrorV1::ProcIo { operation, source })?;
    let mut bytes = Vec::new();
    file.take(limit + 1)
        .read_to_end(&mut bytes)
        .map_err(|source| KfdTargetDebugTelemetryProcessErrorV1::ProcIo { operation, source })?;
    if bytes.len() as u64 > limit {
        return Err(KfdTargetDebugTelemetryProcessErrorV1::ProcFileTooLarge { operation, limit });
    }
    Ok(bytes)
}

fn decode_artifact(
    digest: &[u8],
    length: &[u8],
) -> Result<KfdTargetDebugArtifactIdentityV1, KfdTargetDebugTelemetryProtocolErrorV1> {
    KfdTargetDebugArtifactIdentityV1::new(decode_digest(digest)?, read_u64(length))
        .map_err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayload)
}

fn decode_digest(
    bytes: &[u8],
) -> Result<KfdTargetDebugTelemetryDigestV1, KfdTargetDebugTelemetryProtocolErrorV1> {
    KfdTargetDebugTelemetryDigestV1::from_bytes(bytes.try_into().expect("fixed digest slice"))
        .map_err(KfdTargetDebugTelemetryProtocolErrorV1::InvalidPayload)
}

fn require_payload_len(
    bytes: &[u8],
    expected: usize,
) -> Result<(), KfdTargetDebugTelemetryProtocolErrorV1> {
    if bytes.len() != expected {
        return Err(
            KfdTargetDebugTelemetryProtocolErrorV1::PayloadLengthMismatch {
                expected,
                actual: bytes.len(),
            },
        );
    }
    Ok(())
}

fn require_zero(
    field: &'static str,
    bytes: &[u8],
) -> Result<(), KfdTargetDebugTelemetryProtocolErrorV1> {
    if bytes.iter().any(|byte| *byte != 0) {
        return Err(KfdTargetDebugTelemetryProtocolErrorV1::NonCanonicalReservedBytes(field));
    }
    Ok(())
}

fn put_u32_triplet(output: &mut [u8], value: [u32; 3]) {
    for (index, item) in value.into_iter().enumerate() {
        let offset = index * 4;
        output[offset..offset + 4].copy_from_slice(&item.to_le_bytes());
    }
}

fn read_u32_triplet(bytes: &[u8]) -> [u32; 3] {
    [
        read_u32(&bytes[..4]),
        read_u32(&bytes[4..8]),
        read_u32(&bytes[8..12]),
    ]
}

fn read_u16(bytes: &[u8]) -> u16 {
    u16::from_le_bytes(bytes.try_into().expect("fixed u16 slice"))
}

fn read_u32(bytes: &[u8]) -> u32 {
    u32::from_le_bytes(bytes.try_into().expect("fixed u32 slice"))
}

fn read_u64(bytes: &[u8]) -> u64 {
    u64::from_le_bytes(bytes.try_into().expect("fixed u64 slice"))
}

fn checksum(bytes: &[u8]) -> [u8; 32] {
    let mut digest = Sha256::new();
    digest.update(CHECKSUM_DOMAIN_V1);
    digest.update(bytes);
    digest.finalize().into()
}

fn write_hex(formatter: &mut fmt::Formatter<'_>, bytes: &[u8]) -> fmt::Result {
    for byte in bytes {
        write!(formatter, "{byte:02x}")?;
    }
    Ok(())
}

/// Invalid caller-supplied logical telemetry data.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum KfdTargetDebugTelemetryDataErrorV1 {
    ZeroDigest,
    ZeroNonce,
    ZeroLength,
    ZeroDimension {
        axis: usize,
    },
    WorkgroupExceedsGrid {
        axis: usize,
        grid: u32,
        workgroup: u32,
    },
    InvalidAlignment(u64),
    ZeroDiagnosticCode,
}

impl fmt::Display for KfdTargetDebugTelemetryDataErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ZeroDigest => formatter.write_str("telemetry digest is zero"),
            Self::ZeroNonce => formatter.write_str("telemetry session nonce is zero"),
            Self::ZeroLength => formatter.write_str("telemetry byte length is zero"),
            Self::ZeroDimension { axis } => {
                write!(formatter, "telemetry dimension {axis} is zero")
            }
            Self::WorkgroupExceedsGrid {
                axis,
                grid,
                workgroup,
            } => write!(
                formatter,
                "telemetry workgroup dimension {axis} ({workgroup}) exceeds grid ({grid})"
            ),
            Self::InvalidAlignment(value) => {
                write!(
                    formatter,
                    "telemetry alignment {value} is not a nonzero power of two"
                )
            }
            Self::ZeroDiagnosticCode => formatter.write_str("telemetry diagnostic code is zero"),
        }
    }
}

impl Error for KfdTargetDebugTelemetryDataErrorV1 {}

/// Failure to capture or retain one peer process identity.
#[derive(Debug)]
#[non_exhaustive]
pub enum KfdTargetDebugTelemetryProcessErrorV1 {
    InvalidPid,
    ProcIo {
        operation: &'static str,
        source: std::io::Error,
    },
    ProcFileTooLarge {
        operation: &'static str,
        limit: u64,
    },
    MalformedStat,
    MalformedStatus,
    IdentityChanged,
}

impl fmt::Display for KfdTargetDebugTelemetryProcessErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidPid => formatter.write_str("telemetry peer PID is invalid"),
            Self::ProcIo { operation, source } => {
                write!(
                    formatter,
                    "telemetry peer procfs {operation} failed: {source}"
                )
            }
            Self::ProcFileTooLarge { operation, limit } => write!(
                formatter,
                "telemetry peer procfs {operation} exceeds {limit} bytes"
            ),
            Self::MalformedStat => formatter.write_str("telemetry peer stat is malformed"),
            Self::MalformedStatus => formatter.write_str("telemetry peer status is malformed"),
            Self::IdentityChanged => formatter.write_str("telemetry peer process identity changed"),
        }
    }
}

impl Error for KfdTargetDebugTelemetryProcessErrorV1 {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::ProcIo { source, .. } => Some(source),
            _ => None,
        }
    }
}

/// Canonical record validation failure.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum KfdTargetDebugTelemetryProtocolErrorV1 {
    InvalidWireLength { expected: usize, actual: usize },
    InvalidMagic,
    UnsupportedVersion(u16),
    UnknownKind(u16),
    InvalidPayloadLength { capacity: usize, actual: usize },
    PayloadLengthMismatch { expected: usize, actual: usize },
    ChecksumMismatch,
    NonCanonicalReservedBytes(&'static str),
    InvalidEnum { field: &'static str, value: u16 },
    InvalidPayload(KfdTargetDebugTelemetryDataErrorV1),
    MissingSessionStart,
    DuplicateSessionStart,
    RecordAfterSessionEnd,
}

impl fmt::Display for KfdTargetDebugTelemetryProtocolErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidWireLength { expected, actual } => write!(
                formatter,
                "telemetry wire length mismatch: expected {expected}, got {actual}"
            ),
            Self::InvalidMagic => formatter.write_str("telemetry magic mismatch"),
            Self::UnsupportedVersion(version) => {
                write!(formatter, "unsupported telemetry version {version}")
            }
            Self::UnknownKind(kind) => write!(formatter, "unknown telemetry record kind {kind}"),
            Self::InvalidPayloadLength { capacity, actual } => write!(
                formatter,
                "telemetry payload length {actual} exceeds capacity {capacity}"
            ),
            Self::PayloadLengthMismatch { expected, actual } => write!(
                formatter,
                "telemetry payload length mismatch: expected {expected}, got {actual}"
            ),
            Self::ChecksumMismatch => formatter.write_str("telemetry checksum mismatch"),
            Self::NonCanonicalReservedBytes(field) => {
                write!(formatter, "telemetry {field} bytes are nonzero")
            }
            Self::InvalidEnum { field, value } => {
                write!(formatter, "telemetry {field} value {value} is invalid")
            }
            Self::InvalidPayload(error) => write!(formatter, "invalid telemetry payload: {error}"),
            Self::MissingSessionStart => {
                formatter.write_str("telemetry session did not start with SessionStarted")
            }
            Self::DuplicateSessionStart => {
                formatter.write_str("telemetry session has a duplicate SessionStarted")
            }
            Self::RecordAfterSessionEnd => {
                formatter.write_str("telemetry record follows SessionEnded")
            }
        }
    }
}

impl Error for KfdTargetDebugTelemetryProtocolErrorV1 {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::InvalidPayload(error) => Some(error),
            _ => None,
        }
    }
}

#[derive(Debug)]
#[non_exhaustive]
pub enum KfdInheritedTargetDebugTelemetryErrorV1 {
    IncompleteEnvironment,
    InvalidDescriptor,
    InvalidNonce,
    InvalidDebuggerProcess,
    DebuggerProcess(KfdTargetDebugTelemetryProcessErrorV1),
    DuplicateDescriptor(rustix::io::Errno),
    Admit(KfdTargetDebugTelemetryTransportErrorV1),
    ProtectDescriptor(rustix::io::Errno),
}

impl fmt::Display for KfdInheritedTargetDebugTelemetryErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::IncompleteEnvironment => {
                formatter.write_str("inherited telemetry environment is incomplete")
            }
            Self::InvalidDescriptor => {
                formatter.write_str("inherited telemetry descriptor is invalid")
            }
            Self::InvalidNonce => formatter.write_str("inherited telemetry nonce is invalid"),
            Self::InvalidDebuggerProcess => {
                formatter.write_str("inherited debugger process is invalid")
            }
            Self::DebuggerProcess(error) => write!(formatter, "debugger process binding: {error}"),
            Self::DuplicateDescriptor(error) => {
                write!(
                    formatter,
                    "duplicate inherited telemetry descriptor: {error}"
                )
            }
            Self::Admit(error) => write!(formatter, "admit inherited telemetry endpoint: {error}"),
            Self::ProtectDescriptor(error) => {
                write!(formatter, "protect inherited telemetry descriptor: {error}")
            }
        }
    }
}

impl Error for KfdInheritedTargetDebugTelemetryErrorV1 {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::DebuggerProcess(error) => Some(error),
            Self::Admit(error) => Some(error),
            Self::DuplicateDescriptor(error) | Self::ProtectDescriptor(error) => Some(error),
            _ => None,
        }
    }
}

/// Live telemetry endpoint failure.
#[derive(Debug)]
#[non_exhaustive]
pub enum KfdTargetDebugTelemetryTransportErrorV1 {
    CreateChannel(rustix::io::Errno),
    InspectSocket(rustix::io::Errno),
    ConfigureCredentials(rustix::io::Errno),
    WrongSocketDomain,
    WrongSocketType,
    UnconnectedSocket,
    CredentialsDisabled,
    Process(KfdTargetDebugTelemetryProcessErrorV1),
    PeerCredentialMismatch,
    MissingPeerCredentials,
    ForbiddenAncillaryData,
    AncillaryDataTruncated,
    Send(rustix::io::Errno),
    Receive(rustix::io::Errno),
    PartialSend { expected: usize, actual: usize },
    PacketTruncated,
    InvalidPacketLength { expected: usize, actual: usize },
    UnexpectedEof,
    EndpointNotReady,
    Protocol(KfdTargetDebugTelemetryProtocolErrorV1),
    Data(KfdTargetDebugTelemetryDataErrorV1),
    NonceMismatch,
    SequenceMismatch { expected: u64, actual: u64 },
    SequenceExhausted,
    SessionFinished,
    Poisoned,
}

impl fmt::Display for KfdTargetDebugTelemetryTransportErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::CreateChannel(error) => write!(formatter, "create telemetry channel: {error}"),
            Self::InspectSocket(error) => write!(formatter, "inspect telemetry socket: {error}"),
            Self::ConfigureCredentials(error) => {
                write!(formatter, "configure telemetry credentials: {error}")
            }
            Self::WrongSocketDomain => formatter.write_str("telemetry socket is not AF_UNIX"),
            Self::WrongSocketType => formatter.write_str("telemetry socket is not SOCK_SEQPACKET"),
            Self::UnconnectedSocket => formatter.write_str("telemetry socket is not connected"),
            Self::CredentialsDisabled => {
                formatter.write_str("telemetry socket credentials are disabled")
            }
            Self::Process(error) => write!(formatter, "telemetry process binding: {error}"),
            Self::PeerCredentialMismatch => {
                formatter.write_str("telemetry peer credentials do not match the bound process")
            }
            Self::MissingPeerCredentials => {
                formatter.write_str("telemetry packet has no kernel peer credentials")
            }
            Self::ForbiddenAncillaryData => {
                formatter.write_str("telemetry packet carries forbidden ancillary data")
            }
            Self::AncillaryDataTruncated => {
                formatter.write_str("telemetry packet ancillary data was truncated")
            }
            Self::Send(error) => write!(formatter, "send telemetry packet: {error}"),
            Self::Receive(error) => write!(formatter, "receive telemetry packet: {error}"),
            Self::PartialSend { expected, actual } => write!(
                formatter,
                "telemetry packet send was partial: expected {expected}, got {actual}"
            ),
            Self::PacketTruncated => formatter.write_str("telemetry packet was truncated"),
            Self::InvalidPacketLength { expected, actual } => write!(
                formatter,
                "telemetry packet length mismatch: expected {expected}, got {actual}"
            ),
            Self::UnexpectedEof => {
                formatter.write_str("telemetry endpoint closed before SessionEnded")
            }
            Self::EndpointNotReady => formatter.write_str("telemetry endpoint is not ready"),
            Self::Protocol(error) => write!(formatter, "telemetry protocol: {error}"),
            Self::Data(error) => write!(formatter, "telemetry data: {error}"),
            Self::NonceMismatch => formatter.write_str("telemetry session nonce mismatch"),
            Self::SequenceMismatch { expected, actual } => write!(
                formatter,
                "telemetry sequence mismatch: expected {expected}, got {actual}"
            ),
            Self::SequenceExhausted => formatter.write_str("telemetry sequence exhausted"),
            Self::SessionFinished => formatter.write_str("telemetry session is finished"),
            Self::Poisoned => formatter.write_str("telemetry endpoint is poisoned"),
        }
    }
}

impl Error for KfdTargetDebugTelemetryTransportErrorV1 {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::CreateChannel(error)
            | Self::InspectSocket(error)
            | Self::ConfigureCredentials(error)
            | Self::Send(error)
            | Self::Receive(error) => Some(error),
            Self::Process(error) => Some(error),
            Self::Protocol(error) => Some(error),
            Self::Data(error) => Some(error),
            _ => None,
        }
    }
}

impl From<KfdTargetDebugTelemetryProcessErrorV1> for KfdTargetDebugTelemetryTransportErrorV1 {
    fn from(error: KfdTargetDebugTelemetryProcessErrorV1) -> Self {
        Self::Process(error)
    }
}

impl From<KfdTargetDebugTelemetryProtocolErrorV1> for KfdTargetDebugTelemetryTransportErrorV1 {
    fn from(error: KfdTargetDebugTelemetryProtocolErrorV1) -> Self {
        Self::Protocol(error)
    }
}

impl From<KfdTargetDebugTelemetryDataErrorV1> for KfdTargetDebugTelemetryTransportErrorV1 {
    fn from(error: KfdTargetDebugTelemetryDataErrorV1) -> Self {
        Self::Data(error)
    }
}
