[package]
name = "ferric-build"
description = "Offline authenticated model admission for Ferric"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
ferric-generated-runner = { path = "../ferric-generated-runner" }
ferric-kernels = { path = "../ferric-kernels" }
ferric-spec = { path = "../ferric-spec" }
onig = { version = "=6.5.3", default-features = false }
unicode-normalization-alignments = "=0.1.12"
vstd.workspace = true

[package.metadata.verus]
verify = true

[lints]
workspace = true
