//! Deterministic publication of the inert M1 generated-runner source.
//!
//! The runner declaration renderer in `runner` remains the sole source of
//! generated bytes. This module validates the roadmap path and compiled crate
//! copy against those bytes and provides an atomic developer-tool publication
//! boundary. Source publication grants no artifact, device, queue, execution,
//! proof, performance, or qualification authority.

use std::error::Error;
use std::ffi::OsString;
use std::fmt;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

use ferric_spec::Identity;

use super::runner::{
    render_qwen3_gfx942_runner_source, validate_qwen3_gfx942_runner_source_closure,
};

/// Workspace-relative roadmap path for the inert M1 generated runner.
pub const M1_GENERATED_RUNNER_PATH_V1: &str = "generated/qwen3_m1.rs";
/// Workspace-relative path compiled by `ferric-generated-runner`.
pub const M1_GENERATED_RUNNER_CRATE_SOURCE_PATH_V1: &str =
    "crates/ferric-generated-runner/src/lib.rs";
/// Workspace-relative verified handoff paired with both generated copies.
pub const M1_GENERATED_RUNNER_VALIDATION_SOURCE_PATH_V1: &str =
    "crates/ferric-generated-runner/src/validation.rs";

/// Fail-closed mismatch among the renderer and checked-in generated sources.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum M1GeneratedRunnerSourceErrorV1 {
    /// The roadmap artifact differs from the canonical renderer output.
    RoadmapSourceDrift,
    /// The generated crate differs from the canonical renderer output.
    CrateSourceDrift,
    /// The separately verified handoff module differs from its pinned digest.
    ValidationSourceDrift,
}

impl fmt::Display for M1GeneratedRunnerSourceErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "M1 generated-runner source validation failed: {self:?}"
        )
    }
}

impl Error for M1GeneratedRunnerSourceErrorV1 {}

/// Validates the complete checked-in generated-runner source closure.
///
/// Both the standalone roadmap artifact and the compiled crate source must be
/// byte-for-byte equal to the one canonical renderer output. The validation
/// module must also match the digest and length pinned by the existing runner
/// declaration closure.
///
/// # Errors
///
/// Returns the first exact source class that differs. Digest equality for the
/// validation module is not a proof of SHA-256 collision resistance.
pub fn validate_qwen3_m1_generated_runner_sources_v1(
    roadmap_source: &[u8],
    crate_source: &[u8],
    validation_source: &[u8],
) -> Result<Identity, M1GeneratedRunnerSourceErrorV1> {
    let expected = render_qwen3_gfx942_runner_source();
    if roadmap_source != expected {
        return Err(M1GeneratedRunnerSourceErrorV1::RoadmapSourceDrift);
    }
    if crate_source != expected {
        return Err(M1GeneratedRunnerSourceErrorV1::CrateSourceDrift);
    }
    validate_qwen3_gfx942_runner_source_closure(&expected, validation_source)
        .map_err(|_| M1GeneratedRunnerSourceErrorV1::ValidationSourceDrift)
}

/// Terminal state of one generated-source publication attempt.
#[derive(Debug)]
pub enum M1GeneratedRunnerPublicationStatusV1 {
    /// The destination was already byte-for-byte canonical and was untouched.
    AlreadyCurrent,
    /// Atomic replacement and parent-directory durability sync both succeeded.
    PublishedAndParentDirectorySynced,
    /// Canonical bytes are visible, but syncing the parent directory failed.
    ///
    /// The replacement is already externally visible at this point and cannot
    /// be rolled back without risking removal of another process's observation.
    PublishedButParentDirectorySyncFailed {
        /// Parent directory whose durability sync failed.
        parent_directory: PathBuf,
        /// Exact terminal sync error.
        source: io::Error,
    },
}

/// Failure before canonical generated bytes become visible at the output path.
#[derive(Debug)]
pub enum M1GeneratedRunnerPublicationErrorV1 {
    /// The output path has no final filename component.
    InvalidOutputPath,
    /// Existing-output inspection failed before staging began.
    InspectExisting {
        /// Output path being inspected.
        path: PathBuf,
        /// Exact inspection error.
        source: io::Error,
    },
    /// Staging or atomic replacement failed before publication.
    Io {
        /// Stable operation label.
        operation: &'static str,
        /// Exact path used by the failed operation.
        path: PathBuf,
        /// Exact filesystem error.
        source: io::Error,
    },
}

impl fmt::Display for M1GeneratedRunnerPublicationErrorV1 {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "M1 generated-runner publication failed: {self:?}"
        )
    }
}

impl Error for M1GeneratedRunnerPublicationErrorV1 {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::InspectExisting { source, .. } | Self::Io { source, .. } => Some(source),
            Self::InvalidOutputPath => None,
        }
    }
}

/// Atomically publishes the canonical inert generated runner to `output`.
///
/// A byte-for-byte current regular file is left untouched. Otherwise the
/// complete canonical source is written and synced under a unique staging name
/// in the destination directory, then atomically renamed over the output. Any
/// failure before the rename leaves the prior output unchanged and removes the
/// staging file. A parent-directory sync failure after rename is represented as
/// an explicit successful terminal state because canonical bytes are visible.
///
/// # Errors
///
/// Returns [`M1GeneratedRunnerPublicationErrorV1`] when output inspection,
/// staging, syncing, or the atomic rename fails before publication.
pub fn publish_qwen3_m1_generated_runner_v1(
    output: impl AsRef<Path>,
) -> Result<M1GeneratedRunnerPublicationStatusV1, M1GeneratedRunnerPublicationErrorV1> {
    publish_with(
        output.as_ref(),
        || Ok(()),
        |parent| File::open(parent).and_then(|directory| directory.sync_all()),
    )
}

fn publish_with(
    output: &Path,
    before_rename: impl FnOnce() -> io::Result<()>,
    sync_parent: impl FnOnce(&Path) -> io::Result<()>,
) -> Result<M1GeneratedRunnerPublicationStatusV1, M1GeneratedRunnerPublicationErrorV1> {
    let canonical = render_qwen3_gfx942_runner_source();
    if existing_is_current(output, &canonical)? {
        return Ok(M1GeneratedRunnerPublicationStatusV1::AlreadyCurrent);
    }
    let mut staging = StagingFile::create(output, &canonical)?;
    before_rename().map_err(|source| M1GeneratedRunnerPublicationErrorV1::Io {
        operation: "pre-publication hook",
        path: output.to_path_buf(),
        source,
    })?;
    staging.publish_with(output, sync_parent)
}

fn existing_is_current(
    output: &Path,
    canonical: &[u8],
) -> Result<bool, M1GeneratedRunnerPublicationErrorV1> {
    let metadata = match fs::symlink_metadata(output) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(false),
        Err(source) => {
            return Err(M1GeneratedRunnerPublicationErrorV1::InspectExisting {
                path: output.to_path_buf(),
                source,
            });
        }
    };
    if !metadata.file_type().is_file() || metadata.len() != canonical.len() as u64 {
        return Ok(false);
    }
    let mut file = File::open(output).map_err(|source| {
        M1GeneratedRunnerPublicationErrorV1::InspectExisting {
            path: output.to_path_buf(),
            source,
        }
    })?;
    let mut observed = Vec::new();
    observed
        .try_reserve_exact(canonical.len() + 1)
        .map_err(|_| M1GeneratedRunnerPublicationErrorV1::InspectExisting {
            path: output.to_path_buf(),
            source: io::Error::other("cannot allocate bounded generated-source read buffer"),
        })?;
    Read::by_ref(&mut file)
        .take(canonical.len() as u64 + 1)
        .read_to_end(&mut observed)
        .map_err(
            |source| M1GeneratedRunnerPublicationErrorV1::InspectExisting {
                path: output.to_path_buf(),
                source,
            },
        )?;
    Ok(observed == canonical)
}

struct StagingFile {
    path: PathBuf,
    armed: bool,
}

impl StagingFile {
    fn create(
        output: &Path,
        canonical: &[u8],
    ) -> Result<Self, M1GeneratedRunnerPublicationErrorV1> {
        let parent = output.parent().unwrap_or_else(|| Path::new("."));
        let name = output
            .file_name()
            .ok_or(M1GeneratedRunnerPublicationErrorV1::InvalidOutputPath)?;
        for nonce in 0..1_024_u16 {
            let mut staging_name = OsString::from(".");
            staging_name.push(name);
            staging_name.push(format!(".staging.{}.{nonce}", std::process::id()));
            let path = parent.join(staging_name);
            let file = OpenOptions::new().write(true).create_new(true).open(&path);
            let mut file = match file {
                Ok(file) => file,
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(source) => {
                    return Err(M1GeneratedRunnerPublicationErrorV1::Io {
                        operation: "create staging file",
                        path,
                        source,
                    });
                }
            };
            let staging = Self {
                path: path.clone(),
                armed: true,
            };
            file.write_all(canonical)
                .and_then(|()| file.sync_all())
                .map_err(|source| M1GeneratedRunnerPublicationErrorV1::Io {
                    operation: "write and sync staging file",
                    path,
                    source,
                })?;
            return Ok(staging);
        }
        Err(M1GeneratedRunnerPublicationErrorV1::Io {
            operation: "create unique staging file",
            path: parent.to_path_buf(),
            source: io::Error::new(io::ErrorKind::AlreadyExists, "staging namespace exhausted"),
        })
    }

    fn publish_with(
        &mut self,
        output: &Path,
        sync_parent: impl FnOnce(&Path) -> io::Result<()>,
    ) -> Result<M1GeneratedRunnerPublicationStatusV1, M1GeneratedRunnerPublicationErrorV1> {
        fs::rename(&self.path, output).map_err(|source| {
            M1GeneratedRunnerPublicationErrorV1::Io {
                operation: "atomically replace generated source",
                path: output.to_path_buf(),
                source,
            }
        })?;
        self.armed = false;
        let parent = output.parent().unwrap_or_else(|| Path::new("."));
        Ok(match sync_parent(parent) {
            Ok(()) => M1GeneratedRunnerPublicationStatusV1::PublishedAndParentDirectorySynced,
            Err(source) => {
                M1GeneratedRunnerPublicationStatusV1::PublishedButParentDirectorySyncFailed {
                    parent_directory: parent.to_path_buf(),
                    source,
                }
            }
        })
    }
}

impl Drop for StagingFile {
    fn drop(&mut self) {
        if self.armed {
            let _ = fs::remove_file(&self.path);
        }
    }
}

#[cfg(test)]
mod tests {
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;

    struct TestDirectory(PathBuf);

    impl TestDirectory {
        fn new(label: &str) -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("system clock")
                .as_nanos();
            let path = std::env::temp_dir().join(format!(
                "ferric-m1-generated-runner-{label}-{}-{nonce}",
                std::process::id()
            ));
            fs::create_dir(&path).expect("create test directory");
            Self(path)
        }
    }

    impl Drop for TestDirectory {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn staging_entries(root: &Path) -> Vec<PathBuf> {
        fs::read_dir(root)
            .expect("read test directory")
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| {
                path.file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.contains(".staging."))
            })
            .collect()
    }

    #[test]
    fn checked_in_roadmap_and_crate_sources_are_one_exact_closure() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let roadmap =
            fs::read(root.join(M1_GENERATED_RUNNER_PATH_V1)).expect("checked-in roadmap source");
        let crate_source = fs::read(root.join(M1_GENERATED_RUNNER_CRATE_SOURCE_PATH_V1))
            .expect("checked-in crate source");
        let validation = fs::read(root.join(M1_GENERATED_RUNNER_VALIDATION_SOURCE_PATH_V1))
            .expect("checked-in validation source");
        assert!(validate_qwen3_m1_generated_runner_sources_v1(
            &roadmap,
            &crate_source,
            &validation
        )
        .is_ok());
    }

    #[test]
    fn every_generated_copy_byte_drift_fails_closed() {
        let canonical = render_qwen3_gfx942_runner_source();
        let validation_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../ferric-generated-runner/src/validation.rs");
        let validation = fs::read(validation_path).expect("validation source");
        for index in 0..canonical.len() {
            let mut changed = canonical.clone();
            changed[index] ^= 1;
            assert_eq!(
                validate_qwen3_m1_generated_runner_sources_v1(&changed, &canonical, &validation),
                Err(M1GeneratedRunnerSourceErrorV1::RoadmapSourceDrift)
            );
            assert_eq!(
                validate_qwen3_m1_generated_runner_sources_v1(&canonical, &changed, &validation),
                Err(M1GeneratedRunnerSourceErrorV1::CrateSourceDrift)
            );
        }
        let mut changed_validation = validation.clone();
        changed_validation[0] ^= 1;
        assert_eq!(
            validate_qwen3_m1_generated_runner_sources_v1(
                &canonical,
                &canonical,
                &changed_validation
            ),
            Err(M1GeneratedRunnerSourceErrorV1::ValidationSourceDrift)
        );
        let mut trailing = canonical.clone();
        trailing.push(b'\n');
        assert_eq!(
            validate_qwen3_m1_generated_runner_sources_v1(&trailing, &canonical, &validation),
            Err(M1GeneratedRunnerSourceErrorV1::RoadmapSourceDrift)
        );
        assert_eq!(
            validate_qwen3_m1_generated_runner_sources_v1(
                &canonical[..canonical.len() - 1],
                &canonical,
                &validation
            ),
            Err(M1GeneratedRunnerSourceErrorV1::RoadmapSourceDrift)
        );
    }

    #[test]
    fn publication_is_byte_idempotent() {
        let root = TestDirectory::new("idempotent");
        let output = root.0.join("qwen3_m1.rs");
        assert!(matches!(
            publish_qwen3_m1_generated_runner_v1(&output).unwrap(),
            M1GeneratedRunnerPublicationStatusV1::PublishedAndParentDirectorySynced
        ));
        let before = fs::metadata(&output).unwrap().modified().unwrap();
        assert!(matches!(
            publish_qwen3_m1_generated_runner_v1(&output).unwrap(),
            M1GeneratedRunnerPublicationStatusV1::AlreadyCurrent
        ));
        assert_eq!(fs::metadata(&output).unwrap().modified().unwrap(), before);
        assert_eq!(
            fs::read(&output).unwrap(),
            render_qwen3_gfx942_runner_source()
        );
        assert!(staging_entries(&root.0).is_empty());
    }

    #[test]
    fn drift_is_replaced_only_after_complete_staging() {
        let root = TestDirectory::new("drift");
        let output = root.0.join("qwen3_m1.rs");
        fs::write(&output, b"drifted prior owner").unwrap();
        let result = publish_with(
            &output,
            || Err(io::Error::other("injected before rename")),
            |_| Ok(()),
        );
        assert!(matches!(
            result,
            Err(M1GeneratedRunnerPublicationErrorV1::Io {
                operation: "pre-publication hook",
                source,
                ..
            }) if source.kind() == io::ErrorKind::Other
        ));
        assert_eq!(fs::read(&output).unwrap(), b"drifted prior owner");
        assert!(staging_entries(&root.0).is_empty());

        assert!(publish_qwen3_m1_generated_runner_v1(&output).is_ok());
        assert_eq!(
            fs::read(&output).unwrap(),
            render_qwen3_gfx942_runner_source()
        );
    }

    #[test]
    fn rename_failure_preserves_prior_destination_and_removes_staging() {
        let root = TestDirectory::new("rename-failure");
        let output = root.0.join("qwen3_m1.rs");
        fs::create_dir(&output).unwrap();
        fs::write(output.join("prior-owner"), b"retained").unwrap();
        assert!(matches!(
            publish_qwen3_m1_generated_runner_v1(&output),
            Err(M1GeneratedRunnerPublicationErrorV1::Io {
                operation: "atomically replace generated source",
                ..
            })
        ));
        assert_eq!(fs::read(output.join("prior-owner")).unwrap(), b"retained");
        assert!(staging_entries(&root.0).is_empty());
    }

    #[test]
    fn post_rename_sync_failure_is_explicitly_terminal() {
        let root = TestDirectory::new("sync-failure");
        let output = root.0.join("qwen3_m1.rs");
        let result = publish_with(
            &output,
            || Ok(()),
            |_| {
                Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    "injected sync",
                ))
            },
        )
        .unwrap();
        assert!(matches!(
            result,
            M1GeneratedRunnerPublicationStatusV1::PublishedButParentDirectorySyncFailed {
                parent_directory,
                source,
            } if parent_directory == root.0 && source.kind() == io::ErrorKind::PermissionDenied
        ));
        assert_eq!(
            fs::read(&output).unwrap(),
            render_qwen3_gfx942_runner_source()
        );
        assert!(staging_entries(&root.0).is_empty());
    }

    #[cfg(unix)]
    #[test]
    fn an_exact_symlink_is_replaced_without_mutating_its_target() {
        use std::os::unix::fs::symlink;

        let root = TestDirectory::new("symlink");
        let canonical = render_qwen3_gfx942_runner_source();
        let target = root.0.join("symlink-target.rs");
        let output = root.0.join("qwen3_m1.rs");
        fs::write(&target, &canonical).unwrap();
        symlink(&target, &output).unwrap();

        assert!(matches!(
            publish_qwen3_m1_generated_runner_v1(&output).unwrap(),
            M1GeneratedRunnerPublicationStatusV1::PublishedAndParentDirectorySynced
        ));
        assert!(fs::symlink_metadata(&output).unwrap().file_type().is_file());
        assert_eq!(fs::read(&output).unwrap(), canonical);
        assert_eq!(fs::read(&target).unwrap(), canonical);
    }
}
